# Generated by Django 4.1.13 on 2026-05-15 18:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_classlevelcost_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=datetime.date.today, verbose_name='enrollment date'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], default='active', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='StudentClassroomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred')], default='active', max_length=20, verbose_name='status')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_classroom_assignments', to='academics.academicyear', verbose_name='academic year')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_classroom_assignments', to='academics.classlevel', verbose_name='class level')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='academics.classroom', verbose_name='classroom')),
                ('school_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_classroom_assignments', to='academics.schoollevel', verbose_name='school level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_assignments', to='students.student', verbose_name='student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_classroom_assignments', to='academics.term', verbose_name='term')),
            ],
            options={
                'verbose_name': 'student classroom assignment',
                'verbose_name_plural': 'student classroom assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], default='active', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear', verbose_name='academic year')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classlevel', verbose_name='class level')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classroom', verbose_name='classroom')),
                ('promoted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_students', to='academics.classlevel', verbose_name='promoted from')),
                ('school_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoollevel', verbose_name='school level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_history', to='students.student', verbose_name='student')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.term', verbose_name='term')),
            ],
            options={
                'verbose_name': 'student academic history',
                'verbose_name_plural': 'student academic histories',
                'ordering': ['-academic_year', '-term'],
            },
        ),
        migrations.AddIndex(
            model_name='studentclassroomassignment',
            index=models.Index(fields=['student', 'academic_year', 'term'], name='students_st_student_26e17b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentclassroomassignment',
            index=models.Index(fields=['classroom', 'academic_year'], name='students_st_classro_7dd93e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentclassroomassignment',
            index=models.Index(fields=['status'], name='students_st_status_d29b98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentclassroomassignment',
            unique_together={('student', 'academic_year', 'term')},
        ),
        migrations.AddIndex(
            model_name='studentacademichistory',
            index=models.Index(fields=['student', 'academic_year'], name='students_st_student_c04f32_idx'),
        ),
        migrations.AddIndex(
            model_name='studentacademichistory',
            index=models.Index(fields=['class_level'], name='students_st_class_l_fce6f1_idx'),
        ),
    ]
