# Generated by Django 4.1.13 on 2026-05-05 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_management_alerts', models.BooleanField(default=True)),
                ('grade_alerts', models.BooleanField(default=True)),
                ('assignment_alerts', models.BooleanField(default=True)),
                ('attendance_alerts', models.BooleanField(default=True)),
                ('communication_alerts', models.BooleanField(default=True)),
                ('fee_alerts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_status_changed', 'User Status Changed'), ('user_role_changed', 'User Role Changed'), ('login_success', 'Login Successful'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('grade_uploaded', 'Grade Uploaded'), ('grade_approved', 'Grade Approved'), ('assignment_created', 'Assignment Created'), ('assignment_submitted', 'Assignment Submitted'), ('assignment_graded', 'Assignment Graded'), ('attendance_marked', 'Attendance Marked'), ('low_attendance_warning', 'Low Attendance Warning'), ('message_received', 'Message Received'), ('announcement_posted', 'Announcement Posted'), ('fee_payment_received', 'Payment Received'), ('fee_payment_overdue', 'Payment Overdue'), ('deadline_reminder', 'Deadline Reminder')], db_index=True, max_length=50, verbose_name='notification type')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=20, verbose_name='priority')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], db_index=True, default='unread', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='additional data')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='action URL')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('recipient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status'], name='notificatio_recipie_e285de_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
    ]
