# Generated by Django 4.1.13 on 2026-05-11 07:18

import chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('room_type', models.CharField(choices=[('parent_teacher', 'Parent-Teacher'), ('all_parents', 'All Parents'), ('all_teachers', 'All Teachers'), ('all_students', 'All Students'), ('students_teachers', 'Students and Teachers'), ('students_parents', 'Students and Parents'), ('admin_parent', 'Admin and Parent'), ('admin_teacher', 'Admin and Teacher'), ('parent_teacher_direct', 'Parent and Teacher Direct')], max_length=30, verbose_name='room type')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chatrooms', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatrooms', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'chat room',
                'verbose_name_plural': 'chat rooms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice'), ('audio', 'Audio'), ('video', 'Video'), ('pdf', 'PDF'), ('excel', 'Excel'), ('ppt', 'PowerPoint'), ('word', 'Word'), ('image', 'Image')], default='text', max_length=10, verbose_name='message type')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('file', models.FileField(blank=True, null=True, upload_to=chat.models.message_file_upload_path, verbose_name='file')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='file size')),
                ('is_deleted_by_admin', models.BooleanField(default=False, verbose_name='deleted by admin')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='sent at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='chatroom')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message', verbose_name='reply to')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=10, verbose_name='status')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='chat.message', verbose_name='message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receipts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'message receipt',
                'verbose_name_plural': 'message receipts',
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MessageDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='deleted at')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletions', to='chat.message', verbose_name='message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_messages', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'message deletion',
                'verbose_name_plural': 'message deletions',
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='is hidden')),
                ('can_send_message', models.BooleanField(default=True, verbose_name='can send message')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='last read at')),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.chatroom', verbose_name='chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'chatroom member',
                'verbose_name_plural': 'chatroom members',
                'unique_together': {('chatroom', 'user')},
            },
        ),
    ]
