# Generated by Django 4.1.13 on 2026-05-07 13:06

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_alter_classlevel_code_alter_classlevelcost_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')], verbose_name='email address')),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain 10-15 digits, optionally starting with +', regex='^(\\+?[0-9]{10,15})$')], verbose_name='phone number')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10, verbose_name='gender')),
                ('education_level', models.CharField(choices=[('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate'), ('certificate', 'Certificate')], default='bachelor', max_length=20, verbose_name='education level')),
                ('qualification', models.TextField(blank=True, help_text='List of qualifications', verbose_name='qualification')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='specialization')),
                ('experience_years', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Experience years cannot be negative')], verbose_name='experience years')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('hire_date', models.DateField(default=datetime.date.today, verbose_name='hire date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='status')),
                ('bio', models.TextField(blank=True, verbose_name='biography')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teacher_profiles/', verbose_name='profile picture')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teachers', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='user account')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], default='active', max_length=20, verbose_name='status')),
                ('hours_per_week', models.DecimalField(decimal_places=1, default=4.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(40)], verbose_name='hours per week')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.academicyear', verbose_name='academic year')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teacher_subjects', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.classlevel', verbose_name='class level')),
                ('school_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.schoollevel', verbose_name='school level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject', verbose_name='subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'teacher assignment',
                'verbose_name_plural': 'teacher assignments',
                'ordering': ['teacher', 'school_level', 'class_level', 'subject'],
                'unique_together': {('teacher', 'school_level', 'class_level', 'subject', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='SchoolDaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day of week')),
                ('is_school_day', models.BooleanField(default=True, verbose_name='is school day')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('morning_break_start', models.TimeField(blank=True, null=True, verbose_name='morning break start')),
                ('morning_break_end', models.TimeField(blank=True, null=True, verbose_name='morning break end')),
                ('lunch_break_start', models.TimeField(blank=True, null=True, verbose_name='lunch break start')),
                ('lunch_break_end', models.TimeField(blank=True, null=True, verbose_name='lunch break end')),
                ('afternoon_break_start', models.TimeField(blank=True, null=True, verbose_name='afternoon break start')),
                ('afternoon_break_end', models.TimeField(blank=True, null=True, verbose_name='afternoon break end')),
                ('events', models.JSONField(blank=True, default=list, help_text='List of events for this day', verbose_name='special events')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_settings', to='academics.academicyear', verbose_name='academic year')),
                ('school_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_settings', to='academics.schoollevel', verbose_name='school level')),
            ],
            options={
                'verbose_name': 'school day setting',
                'verbose_name_plural': 'school day settings',
                'ordering': ['school_level', 'day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('date', models.DateField(verbose_name='date')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='is recurring yearly')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='academics.academicyear', verbose_name='academic year')),
                ('school_level', models.ForeignKey(blank=True, help_text='Leave blank for all school levels', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='academics.schoollevel', verbose_name='school level')),
            ],
            options={
                'verbose_name': 'holiday',
                'verbose_name_plural': 'holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day of week')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('week_number', models.PositiveIntegerField(default=1, verbose_name='week number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.academicyear', verbose_name='academic year')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='teachers.teacherassignment', verbose_name='assignment')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.classlevel', verbose_name='class level')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.classroom', verbose_name='classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.subject', verbose_name='subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='teachers.teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'teacher timetable',
                'verbose_name_plural': 'teacher timetables',
                'ordering': ['teacher', 'day_of_week', 'start_time'],
                'unique_together': {('classroom', 'day_of_week', 'start_time', 'academic_year', 'week_number'), ('teacher', 'day_of_week', 'start_time', 'academic_year', 'week_number')},
            },
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['email'], name='teachers_te_email_886f02_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['phone_number'], name='teachers_te_phone_n_4c0ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['status'], name='teachers_te_status_cc7a79_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['full_name'], name='teachers_te_full_na_e7daa7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schooldaysetting',
            unique_together={('school_level', 'day_of_week', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('date', 'school_level', 'academic_year')},
        ),
    ]
