# Generated by Django 4.1.13 on 2026-05-13 07:29

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import teachers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0009_schoollevel_end_time_schoollevel_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='last name')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='middle name')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address')], verbose_name='email address')),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain 10-15 digits, optionally starting with +', regex='^(\\+?[0-9]{10,15})$')], verbose_name='phone number')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10, verbose_name='gender')),
                ('salary', models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Salary cannot be negative')], verbose_name='salary')),
                ('work_hours_per_week', models.DecimalField(decimal_places=1, default=40.0, max_digits=4, validators=[django.core.validators.MinValueValidator(1, message='Work hours must be at least 1'), django.core.validators.MaxValueValidator(60, message='Work hours cannot exceed 60')], verbose_name='work hours per week')),
                ('education_level', models.CharField(choices=[('a2', 'A2 (Secondary School Certificate)'), ('a1', 'A1 (Advanced Diploma)'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate'), ('certificate', 'Certificate')], default='bachelor', max_length=20, verbose_name='education level')),
                ('qualifications', models.TextField(blank=True, help_text='List of qualifications and achievements', verbose_name='qualifications')),
                ('qualification_document', models.FileField(blank=True, null=True, upload_to=teachers.models.teacher_qualification_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png'])], verbose_name='qualification document')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('hire_date', models.DateField(default=datetime.date.today, verbose_name='hire date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='status')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=teachers.models.teacher_profile_picture_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='profile picture')),
                ('bio', models.TextField(blank=True, verbose_name='biography')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teachers', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('specializations', models.ManyToManyField(blank=True, help_text='Subjects this teacher is specialized in', related_name='specialized_teachers', to='academics.subject', verbose_name='specializations')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='user account')),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], default='active', max_length=20, verbose_name='status')),
                ('hours_per_week', models.DecimalField(decimal_places=1, default=4.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(40)], verbose_name='hours per week')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('academic_year', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.academicyear', verbose_name='academic year')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teacher_subjects', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('class_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.classlevel', verbose_name='class level')),
                ('classroom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.classroom', verbose_name='classroom')),
                ('school_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.schoollevel', verbose_name='school level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject', verbose_name='subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.teacher', verbose_name='teacher')),
                ('term', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.term', verbose_name='term')),
            ],
            options={
                'verbose_name': 'teacher assignment',
                'verbose_name_plural': 'teacher assignments',
                'ordering': ['academic_year', 'term', 'teacher', 'school_level', 'class_level'],
            },
        ),
        migrations.CreateModel(
            name='TeacherTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day of week')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('week_number', models.PositiveIntegerField(default=1, verbose_name='week number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_timetables', to='academics.academicyear', verbose_name='academic year')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='teachers.teacherassignment', verbose_name='assignment')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.classlevel', verbose_name='class level')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.classroom', verbose_name='classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetables', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('school_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.schoollevel', verbose_name='school level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.subject', verbose_name='subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='teachers.teacher', verbose_name='teacher')),
                ('term', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_timetables', to='academics.term', verbose_name='term')),
            ],
            options={
                'verbose_name': 'teacher timetable',
                'verbose_name_plural': 'teacher timetables',
                'ordering': ['teacher', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TeacherDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('qualification', 'Qualification Certificate'), ('id_document', 'ID Document'), ('contract', 'Employment Contract'), ('certificate', 'Training Certificate'), ('other', 'Other Document')], default='other', max_length=20, verbose_name='document type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(upload_to=teachers.models.teacher_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'png', 'xls', 'xlsx'])], verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='teachers.teacher', verbose_name='teacher')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'teacher document',
                'verbose_name_plural': 'teacher documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='teachertimetable',
            index=models.Index(fields=['academic_year', 'term', 'teacher'], name='teachers_te_academi_cb3393_idx'),
        ),
        migrations.AddIndex(
            model_name='teachertimetable',
            index=models.Index(fields=['academic_year', 'term', 'classroom'], name='teachers_te_academi_919d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='teachertimetable',
            index=models.Index(fields=['academic_year', 'term', 'day_of_week'], name='teachers_te_academi_a2c56b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teachertimetable',
            unique_together={('academic_year', 'term', 'day_of_week', 'start_time', 'classroom'), ('academic_year', 'term', 'day_of_week', 'start_time', 'teacher')},
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['teacher', 'status'], name='teachers_te_teacher_3e6ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['academic_year', 'term'], name='teachers_te_academi_5afaa4_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['class_level', 'subject'], name='teachers_te_class_l_1d39f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher', 'academic_year', 'term', 'class_level', 'subject', 'classroom')},
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['email'], name='teachers_te_email_886f02_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['phone_number'], name='teachers_te_phone_n_4c0ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['status'], name='teachers_te_status_cc7a79_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['first_name', 'last_name'], name='teachers_te_first_n_a00cdc_idx'),
        ),
    ]
