# Generated by Django 4.1.13 on 2026-05-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachertimetable',
            name='school_level',
        ),
    ]
