# Generated by Django 4.1.13 on 2026-05-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_picture_mime',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='profile picture mime type'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.BinaryField(blank=True, editable=True, null=True, verbose_name='profile picture'),
        ),
    ]
