# Generated by Django 4.1.13 on 2026-05-19 09:12

import academics_records.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0013_alter_classlevelcost_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0002_teacher_profile_picture_mime_and_more'),
        ('students', '0002_student_enrollment_date_alter_parent_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to=academics_records.models.attendance_upload_path)),
                ('is_submitted', models.BooleanField(db_index=True, default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academics.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academics.classlevel')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='academics.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendance_sessions', to=settings.AUTH_USER_MODEL)),
                ('school_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academics.schoollevel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='teachers.teacher')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academics.term')),
            ],
            options={
                'verbose_name': 'attendance session',
                'verbose_name_plural': 'attendance sessions',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='GradeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('mid_term', 'Mid-Term Exam'), ('final_exam', 'Final Exam'), ('project', 'Project'), ('practical', 'Practical'), ('oral', 'Oral Assessment'), ('homework', 'Homework')], default='assignment', max_length=30)),
                ('weight_percentage', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5)),
                ('max_score_possible', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=6)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('excel_file', models.FileField(upload_to=academics_records.models.grade_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])])),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_review', 'Needs Review')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_uploads', to='academics.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_uploads', to='academics.classlevel')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_uploads', to='academics.classroom')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_grade_uploads', to=settings.AUTH_USER_MODEL)),
                ('school_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_uploads', to='academics.schoollevel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_uploads', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_uploads', to='teachers.teacher')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_uploads', to='academics.term')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_grade_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'grade upload',
                'verbose_name_plural': 'grade uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=6)),
                ('remarks', models.TextField(blank=True)),
                ('custom_grade_letter', models.CharField(blank=True, max_length=5)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='academics_records.gradeupload')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
            ],
            options={
                'verbose_name': 'student grade',
                'verbose_name_plural': 'student grades',
                'ordering': ['student__full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], db_index=True, default='present', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='academics_records.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
            ],
            options={
                'verbose_name': 'student attendance',
                'verbose_name_plural': 'student attendances',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('pdf_file', models.FileField(upload_to='assignments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_assignment_files', to='academics.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_assignment_files', to='academics.classlevel')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_assignment_files', to='academics.classroom')),
                ('school_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_assignment_files', to='academics.schoollevel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_assignment_files', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_assignment_files', to='teachers.teacher')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_assignment_files', to='academics.term')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentgrade',
            index=models.Index(fields=['student', 'is_published'], name='academics_r_student_8e7172_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentgrade',
            unique_together={('grade_upload', 'student')},
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['status'], name='academics_r_status_792dad_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['student', 'status'], name='academics_r_student_c3378f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('session', 'student')},
        ),
        migrations.AddIndex(
            model_name='gradeupload',
            index=models.Index(fields=['status'], name='academics_r_status_b36f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeupload',
            index=models.Index(fields=['teacher', 'academic_year'], name='academics_r_teacher_0b4d88_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeupload',
            index=models.Index(fields=['class_level', 'subject'], name='academics_r_class_l_59aaaa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradeupload',
            unique_together={('teacher', 'academic_year', 'term', 'class_level', 'subject', 'grade_type')},
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['session_date', 'teacher'], name='academics_r_session_4049ff_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['class_level', 'session_date'], name='academics_r_class_l_869dc2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('teacher', 'class_level', 'subject', 'session_date', 'academic_year')},
        ),
    ]
