# Generated by Django 4.1.13 on 2026-05-05 16:07

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 2024-2025', max_length=100, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], default='inactive', max_length=20, verbose_name='status')),
                ('is_current', models.BooleanField(default=False, verbose_name='is current')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'academic year',
                'verbose_name_plural': 'academic years',
                'ordering': ['-start_date'],
                'unique_together': {('name', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Primary 1, Senior 1', max_length=50, verbose_name='name')),
                ('category', models.CharField(choices=[('pre_primary', 'Pre-Primary'), ('primary', 'Primary'), ('ordinary_level', 'Ordinary Level (S1-S3)'), ('advanced_level', 'Advanced Level (S4-S6)')], max_length=20, verbose_name='category')),
                ('code', models.CharField(help_text='e.g., P1, S1', max_length=20, unique=True, verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.IntegerField(default=0, help_text='Display order', verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_teaching_frequency', models.CharField(choices=[('daily', 'Daily (Everyday)'), ('weekly', 'Weekly (Once a week)'), ('bi_weekly', 'Bi-Weekly (Twice a week)')], default='daily', help_text='Default frequency for subjects taught at this level', max_length=20, verbose_name='default teaching frequency')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'class level',
                'verbose_name_plural': 'class levels',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., A, B, C, or Alpha, Beta', max_length=50, verbose_name='name')),
                ('full_name', models.CharField(blank=True, help_text='e.g., Primary 1A', max_length=100, verbose_name='full name')),
                ('code', models.CharField(help_text='e.g., P1A, P1B', max_length=20, unique=True, verbose_name='code')),
                ('room_type', models.CharField(choices=[('standard', 'Standard Classroom'), ('laboratory', 'Laboratory'), ('workshop', 'Workshop'), ('studio', 'Studio')], default='standard', max_length=20, verbose_name='room type')),
                ('shift', models.CharField(choices=[('morning', 'Morning Shift'), ('afternoon', 'Afternoon Shift'), ('evening', 'Evening Shift'), ('full_day', 'Full Day')], default='morning', max_length=20, verbose_name='shift')),
                ('capacity', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='capacity')),
                ('current_enrollment', models.PositiveIntegerField(default=0, verbose_name='current enrollment')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_rooms', to='academics.classlevel', verbose_name='class level')),
                ('homeroom_teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to=settings.AUTH_USER_MODEL, verbose_name='homeroom teacher')),
            ],
            options={
                'verbose_name': 'class room',
                'verbose_name_plural': 'class rooms',
                'ordering': ['class_level', 'name'],
                'unique_together': {('class_level', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Primary School', max_length=100, verbose_name='name')),
                ('level_type', models.CharField(choices=[('pre_primary', 'Pre-Primary'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('high_school', 'High School')], max_length=20, verbose_name='level type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.IntegerField(default=0, help_text='Display order', verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'school level',
                'verbose_name_plural': 'school levels',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Mathematics', max_length=100, verbose_name='name')),
                ('code', models.CharField(help_text='e.g., MATH101', max_length=20, unique=True, verbose_name='code')),
                ('category', models.CharField(choices=[('core', 'Core Subject'), ('elective', 'Elective'), ('vocational', 'Vocational'), ('extra_curricular', 'Extra Curricular')], default='core', max_length=20, verbose_name='category')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('grading_system', models.CharField(choices=[('numeric', 'Numeric (0-100)'), ('letter', 'Letter Grade (A-F)'), ('pass_fail', 'Pass/Fail')], default='numeric', max_length=20, verbose_name='grading system')),
                ('pass_mark', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='pass mark')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class', max_length=50, verbose_name='icon')),
                ('color', models.CharField(blank=True, help_text='CSS color code', max_length=20, verbose_name='color')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassLevelSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_frequency', models.CharField(choices=[('daily', 'Daily (Everyday)'), ('weekly', 'Weekly (Once a week)'), ('bi_weekly', 'Bi-Weekly (Twice a week)')], help_text='How often this subject is taught', max_length=20, verbose_name='teaching frequency')),
                ('hours_per_week', models.DecimalField(decimal_places=1, default=4.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(40)], verbose_name='hours per week')),
                ('hours_per_day', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)], verbose_name='hours per day')),
                ('term_offered', models.CharField(choices=[('term_1', 'Term 1'), ('term_2', 'Term 2'), ('term_3', 'Term 3'), ('full_year', 'Full Year')], default='full_year', max_length=20, verbose_name='term offered')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('dropped', 'Dropped')], default='active', max_length=20, verbose_name='status')),
                ('is_compulsory', models.BooleanField(default=True, verbose_name='is compulsory')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('order', models.IntegerField(default=0, help_text='Display order in curriculum', verbose_name='order')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_level_subjects', to='academics.classlevel', verbose_name='class level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_level_subjects', to='academics.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'class level subject',
                'verbose_name_plural': 'class level subjects',
                'ordering': ['class_level', 'order', 'subject__name'],
                'unique_together': {('class_level', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ClassLevelCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Primary 1 Tuition', max_length=100, verbose_name='name')),
                ('payment_type', models.CharField(choices=[('tuition', 'Tuition Fee'), ('registration', 'Registration Fee'), ('examination', 'Examination Fee'), ('library', 'Library Fee'), ('sports', 'Sports Fee'), ('laboratory', 'Laboratory Fee'), ('uniform', 'Uniform Fee'), ('transport', 'Transport Fee'), ('meal', 'Meal Fee'), ('other', 'Other')], max_length=20, verbose_name='payment type')),
                ('frequency', models.CharField(choices=[('one_time', 'One Time'), ('termly', 'Termly'), ('annually', 'Annually'), ('monthly', 'Monthly')], max_length=20, verbose_name='frequency')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='is mandatory')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_level_costs', to='academics.academicyear', verbose_name='academic year')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='academics.classlevel', verbose_name='class level')),
            ],
            options={
                'verbose_name': 'class level cost',
                'verbose_name_plural': 'class level costs',
                'ordering': ['class_level', 'payment_type', 'amount'],
            },
        ),
        migrations.AddField(
            model_name='classlevel',
            name='school_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='academics.schoollevel', verbose_name='school level'),
        ),
        migrations.CreateModel(
            name='ClassRoomSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_week', models.JSONField(default=list, help_text='List of days (0-6)', verbose_name='days of week')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('class_level_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_room_subjects', to='academics.classlevelsubject', verbose_name='class level subject')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_room_subjects', to='academics.classroom', verbose_name='class room')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_subjects', to=settings.AUTH_USER_MODEL, verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'class room subject',
                'verbose_name_plural': 'class room subjects',
                'unique_together': {('class_room', 'class_level_subject')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classlevel',
            unique_together={('name', 'school_level')},
        ),
    ]
