# Generated by Django 4.1.13 on 2026-05-07 06:14

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Year name must be in format YYYY-YYYY (e.g., 2024-2025)', regex='^\\d{4}-\\d{4}$')], verbose_name='name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('is_current', models.BooleanField(default=False, verbose_name='is current')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'academic year',
                'verbose_name_plural': 'academic years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Class code must be uppercase letters and numbers only', regex='^[A-Z0-9]+$')], verbose_name='code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'class level',
                'verbose_name_plural': 'class levels',
                'ordering': ['school_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='School level name can only contain letters, spaces, and hyphens', regex='^[a-zA-Z\\s\\-]+$')], verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'school level',
                'verbose_name_plural': 'school levels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Subject code must be uppercase letters and numbers only', regex='^[A-Z0-9]+$')], verbose_name='code')),
                ('pass_mark', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='pass mark')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Room code must be uppercase letters and numbers only', regex='^[A-Z0-9]+$')], verbose_name='code')),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('laboratory', 'Laboratory'), ('workshop', 'Workshop'), ('auditorium', 'Auditorium')], default='standard', max_length=20, verbose_name='room type')),
                ('capacity', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='capacity')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='academics.classlevel')),
            ],
            options={
                'verbose_name': 'class room',
                'verbose_name_plural': 'class rooms',
                'ordering': ['class_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassLevelSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20, verbose_name='teaching frequency')),
                ('hours_per_week', models.DecimalField(decimal_places=1, default=4.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(40)], verbose_name='hours per week')),
                ('is_compulsory', models.BooleanField(default=True, verbose_name='is compulsory')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.classlevel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='academics.subject')),
            ],
            options={
                'verbose_name': 'class level subject',
                'verbose_name_plural': 'class level subjects',
            },
        ),
        migrations.CreateModel(
            name='ClassLevelCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('frequency', models.CharField(choices=[('termly', 'Termly'), ('yearly', 'Yearly'), ('monthly', 'Monthly')], default='termly', max_length=20, verbose_name='frequency')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='is mandatory')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='academics.academicyear')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='academics.classlevel')),
            ],
            options={
                'verbose_name': 'fee structure',
                'verbose_name_plural': 'fee structures',
                'ordering': ['class_level', 'name'],
            },
        ),
        migrations.AddField(
            model_name='classlevel',
            name='school_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='academics.schoollevel'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['name'], name='academics_a_name_9decb9_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['is_current'], name='academics_a_is_curr_2481be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('class_level', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classlevelsubject',
            unique_together={('class_level', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='classlevelcost',
            unique_together={('class_level', 'name', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='classlevel',
            unique_together={('name', 'school_level')},
        ),
    ]
