# Generated by Django 4.1.13 on 2026-05-07 13:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevel',
            name='code',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Class code must contain only uppercase letters and numbers', regex='^[A-Z0-9]+$')], verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='classlevelcost',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Amount must be greater than 0')], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='classlevelsubject',
            name='hours_per_week',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.5, message='Hours per week must be at least 0.5'), django.core.validators.MaxValueValidator(40, message='Hours per week cannot exceed 40')], verbose_name='hours per week'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1, message='Capacity must be at least 1'), django.core.validators.MaxValueValidator(200, message='Capacity cannot exceed 200')], verbose_name='capacity'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Room code must contain only uppercase letters and numbers', regex='^[A-Z0-9]+$')], verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Subject code must contain only uppercase letters and numbers', regex='^[A-Z0-9]+$')], verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='pass_mark',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Pass mark cannot be less than 0'), django.core.validators.MaxValueValidator(100, message='Pass mark cannot exceed 100')], verbose_name='pass mark'),
        ),
    ]
