# Generated by Django 4.1.13 on 2026-05-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_fix_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevelcost',
            name='payment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='academics.paymenttype'),
        ),
    ]
