# Generated by Django 4.1.13 on 2026-05-13 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_classlevelcost_payment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['name'], 'verbose_name': 'class room', 'verbose_name_plural': 'class rooms'},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name',)},
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='class_level',
        ),
    ]
