# Generated by Django 4.1.13 on 2026-05-13 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_add_classroom_assignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('name', 'code')},
        ),
    ]
