# Generated by Django 4.1.13 on 2026-05-13 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_classroom_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='break name')),
                ('break_type', models.CharField(choices=[('short_break', 'Short Break'), ('lunch', 'Lunch Break'), ('recess', 'Recess'), ('other', 'Other')], default='short_break', max_length=20, verbose_name='break type')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('duration_minutes', models.PositiveIntegerField(editable=False, help_text='Automatically calculated from start and end time', verbose_name='duration (minutes)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('school_level', models.ForeignKey(help_text='School level this break applies to', on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='academics.schoollevel')),
            ],
            options={
                'verbose_name': 'school break',
                'verbose_name_plural': 'school breaks',
                'ordering': ['school_level', 'start_time'],
                'unique_together': {('school_level', 'name')},
            },
        ),
    ]
