# Generated by Django 4.1.13 on 2026-05-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_schoolbreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollevel',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Daily end time for this school level (e.g. 16:00)', null=True, verbose_name='end time'),
        ),
        migrations.AddField(
            model_name='schoollevel',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Daily start time for this school level (e.g. 08:00)', null=True, verbose_name='start time'),
        ),
    ]
