# Generated by Django 4.1.13 on 2026-05-13 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_schoollevel_end_time_schoollevel_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('date', models.DateField(verbose_name='date')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='is recurring yearly')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='academics.academicyear', verbose_name='academic year')),
                ('school_level', models.ForeignKey(blank=True, help_text='Leave blank for all school levels', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='academics.schoollevel', verbose_name='school level')),
            ],
            options={
                'verbose_name': 'holiday',
                'verbose_name_plural': 'holidays',
                'ordering': ['date'],
                'unique_together': {('date', 'school_level', 'academic_year')},
            },
        ),
    ]
