# Generated by Django 4.1.13 on 2026-05-14 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_holiday'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='school_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='academics.schoollevel', verbose_name='school level'),
        ),
        migrations.AlterField(
            model_name='classlevelcost',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='academics.academicyear', verbose_name='academic year'),
        ),
        migrations.AlterField(
            model_name='classlevelcost',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='academics.classlevel', verbose_name='class level'),
        ),
        migrations.AlterField(
            model_name='classlevelcost',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='classlevelcost',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='academics.paymenttype', verbose_name='payment type'),
        ),
        migrations.AlterField(
            model_name='classlevelsubject',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.classlevel', verbose_name='class level'),
        ),
        migrations.AlterField(
            model_name='classlevelsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='academics.subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='classroomassignment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_assignments', to='academics.academicyear', verbose_name='academic year'),
        ),
        migrations.AlterField(
            model_name='classroomassignment',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_assignments', to='academics.classlevel', verbose_name='class level'),
        ),
        migrations.AlterField(
            model_name='classroomassignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.classroom', verbose_name='classroom'),
        ),
        migrations.AlterField(
            model_name='classroomassignment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_assignments', to='academics.term', verbose_name='term'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='schoolbreak',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='schoolbreak',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Automatically calculated from start and end time', verbose_name='duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='schoolbreak',
            name='school_level',
            field=models.ForeignKey(help_text='School level this break applies to', on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='academics.schoollevel', verbose_name='school level'),
        ),
        migrations.AlterField(
            model_name='schooldaysetting',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_year_day_settings', to='academics.academicyear', verbose_name='academic year'),
        ),
        migrations.AlterField(
            model_name='schooldaysetting',
            name='day_type',
            field=models.CharField(choices=[('learning', 'Learning Day'), ('day_off', 'Day Off'), ('special', 'Special Learning Day')], default='learning', max_length=20, verbose_name='day type'),
        ),
        migrations.AlterField(
            model_name='schooldaysetting',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='schoollevel',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear', verbose_name='academic year'),
        ),
    ]
