# Generated by Django 4.1.13 on 2026-05-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_alter_classroom_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='assigned_class_level',
            field=models.OneToOneField(blank=True, help_text='The class level currently assigned to this classroom. Each classroom can be assigned to only one class level.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classroom', to='academics.classlevel', verbose_name='assigned class level'),
        ),
        migrations.DeleteModel(
            name='ClassroomAssignment',
        ),
    ]
