# Generated by Django 4.1.13 on 2026-05-14 15:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_classroom_assigned_class_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevelcost',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Amount must be greater than 0'), django.core.validators.MaxValueValidator(Decimal('99999999.99'), message='Amount cannot exceed 99,999,999.99')], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='assigned_class_level',
            field=models.ForeignKey(blank=True, help_text='The class level currently assigned to this classroom.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classrooms', to='academics.classlevel', verbose_name='assigned class level'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['start_date', 'end_date'], name='academics_a_start_d_e0fea6_idx'),
        ),
        migrations.AddIndex(
            model_name='classlevel',
            index=models.Index(fields=['code'], name='academics_c_code_d7e965_idx'),
        ),
        migrations.AddIndex(
            model_name='classlevel',
            index=models.Index(fields=['school_level', 'is_active'], name='academics_c_school__4914b3_idx'),
        ),
        migrations.AddIndex(
            model_name='classlevelcost',
            index=models.Index(fields=['class_level', 'academic_year'], name='academics_c_class_l_2e3f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='classlevelcost',
            index=models.Index(fields=['payment_type'], name='academics_c_payment_a77f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='classlevelsubject',
            index=models.Index(fields=['class_level', 'subject'], name='academics_c_class_l_86ba72_idx'),
        ),
        migrations.AddIndex(
            model_name='classlevelsubject',
            index=models.Index(fields=['teaching_frequency'], name='academics_c_teachin_442af2_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['code'], name='academics_c_code_d2babb_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['status'], name='academics_c_status_cb297e_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['assigned_class_level'], name='academics_c_assigne_dae2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date'], name='academics_h_date_14b607_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['academic_year', 'is_recurring'], name='academics_h_academi_0b78db_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttype',
            index=models.Index(fields=['code'], name='academics_p_code_e85c77_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttype',
            index=models.Index(fields=['is_active'], name='academics_p_is_acti_dbac5e_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolbreak',
            index=models.Index(fields=['school_level', 'is_active'], name='academics_s_school__525003_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolbreak',
            index=models.Index(fields=['break_type'], name='academics_s_break_t_a44550_idx'),
        ),
        migrations.AddIndex(
            model_name='schooldaysetting',
            index=models.Index(fields=['academic_year', 'day_type'], name='academics_s_academi_78aaff_idx'),
        ),
        migrations.AddIndex(
            model_name='schooldaysetting',
            index=models.Index(fields=['specific_date'], name='academics_s_specifi_c14c64_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='academics_s_code_3689e5_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['status'], name='academics_s_status_b0a6a9_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['academic_year', 'is_current'], name='academics_t_academi_f0b349_idx'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['start_date', 'end_date'], name='academics_t_start_d_6589d2_idx'),
        ),
    ]
