# Generated by Django 4.1.13 on 2026-05-11 12:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_alter_classlevel_code_alter_classlevelcost_amount_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPaymentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Amount must be greater than 0')], verbose_name='total amount')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='Paid amount cannot be negative')], verbose_name='paid amount')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='remaining amount')),
                ('payment_start_date', models.DateField(default=django.utils.timezone.now, verbose_name='payment start date')),
                ('payment_due_date', models.DateField(verbose_name='payment due date')),
                ('payment_extended_until', models.DateField(blank=True, null=True, verbose_name='payment extended until')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue')], default='waiting', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_assignments', to='academics.academicyear', verbose_name='academic year')),
                ('class_level_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='academics.classlevelcost', verbose_name='fee structure')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_assignments', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_assignments', to='students.student', verbose_name='student')),
            ],
            options={
                'verbose_name': 'student payment assignment',
                'verbose_name_plural': 'student payment assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Amount must be greater than 0')], verbose_name='amount')),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20, verbose_name='payment method')),
                ('payment_type', models.CharField(choices=[('fully_paid', 'Fully Paid'), ('partially_paid', 'Partially Paid')], default='partially_paid', max_length=20, verbose_name='payment type')),
                ('transaction_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='transaction status')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number used for mobile money payment', max_length=20, null=True, verbose_name='phone number')),
                ('mobile_money_provider', models.CharField(blank=True, choices=[('mtn', 'MTN'), ('airtel', 'Airtel'), ('tigo', 'Tigo')], max_length=50, null=True, verbose_name='mobile money provider')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='transaction reference')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='bank name')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='bank account number')),
                ('bank_receipt_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='bank receipt number')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='receipt number')),
                ('payment_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.studentpaymentassignment', verbose_name='payment assignment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'payment transaction',
                'verbose_name_plural': 'payment transactions',
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentpaymentassignment',
            index=models.Index(fields=['student', 'status'], name='payments_st_student_e0d610_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpaymentassignment',
            index=models.Index(fields=['academic_year', 'status'], name='payments_st_academi_e9901f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpaymentassignment',
            index=models.Index(fields=['payment_due_date'], name='payments_st_payment_76f4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpaymentassignment',
            index=models.Index(fields=['status'], name='payments_st_status_04e2e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentpaymentassignment',
            unique_together={('student', 'class_level_cost', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_reference'], name='payments_pa_transac_91c5f8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_status'], name='payments_pa_transac_cc1678_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['paid_at'], name='payments_pa_paid_at_57b3fb_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_assignment', 'transaction_status'], name='payments_pa_payment_3fa709_idx'),
        ),
    ]
